[build]
  base      = "Hungrydeal-code/frontend/web"
  command   = "npm install --legacy-peer-deps && npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS    = "--legacy-peer-deps"
  NEXT_PUBLIC_API_URL = "https://hungrydeal-api.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
